CREATE USER lds WITH PASSWORD 'lds';
CREATE DATABASE lds;
GRANT ALL PRIVILEGES ON DATABASE lds TO lds;

CREATE USER sagalog WITH PASSWORD 'sagalog';
CREATE DATABASE sagalog;
GRANT ALL PRIVILEGES ON DATABASE sagalog TO sagalog;
